/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_gramlab_kwaga_unitex_uima_unitex_UnitexJNI */

#ifndef _Included_org_gramlab_kwaga_unitex_uima_unitex_UnitexJNI
#define _Included_org_gramlab_kwaga_unitex_uima_unitex_UnitexJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_gramlab_kwaga_unitex_uima_unitex_UnitexJNI
 * Method:    UnitexTool
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_gramlab_kwaga_unitex_1uima_unitex_UnitexJNI_UnitexTool
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     org_gramlab_kwaga_unitex_uima_unitex_UnitexJNI
 * Method:    setStdOutFile
 * Signature: (Ljava/lang/String;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_org_gramlab_kwaga_unitex_1uima_unitex_UnitexJNI_setStdOutFile
  (JNIEnv *, jclass, jstring, jboolean);

/*
 * Class:     org_gramlab_kwaga_unitex_uima_unitex_UnitexJNI
 * Method:    installLogger
 * Signature: (Ljava/lang/String;Z)J
 */
JNIEXPORT jlong JNICALL Java_org_gramlab_kwaga_unitex_1uima_unitex_UnitexJNI_installLogger
  (JNIEnv *, jclass, jstring, jboolean);

/*
 * Class:     org_gramlab_kwaga_unitex_uima_unitex_UnitexJNI
 * Method:    selectNextLogName
 * Signature: (JLjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_gramlab_kwaga_unitex_1uima_unitex_UnitexJNI_selectNextLogName
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     org_gramlab_kwaga_unitex_uima_unitex_UnitexJNI
 * Method:    uninstallLogger
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_gramlab_kwaga_unitex_1uima_unitex_UnitexJNI_uninstallLogger
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_gramlab_kwaga_unitex_uima_unitex_UnitexJNI
 * Method:    getUnitexRevision
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_gramlab_kwaga_unitex_1uima_unitex_UnitexJNI_getUnitexRevision
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
